Add checks for dependencies

diff --git a/bin-wrapper/align-all-docker b/bin-wrapper/align-all-docker
--- a/bin-wrapper/align-all-docker
+++ b/bin-wrapper/align-all-docker
@@ -1,6 +1,29 @@
 #! /bin/bash
 
+SYSTEM=$(uname -s)
+REALPATH_CMD=$(which realpath)
+DOCKER_CMD=$(which docker)
+
+BOLD="\x1b[1m"
+NORM="\x1b[0m"
+
 set -e
+
+if [ ! -f "$REALPATH_CMD" ]; then
+  echo "Command dependency 'realpath' is not found/installed." >&2
+  case "${SYSTEM}" in
+    Darwin*)
+      echo -e "To install using Homebrew (https://brew.sh/): ${BOLD}brew install coreutils${NORM}" >&2
+      ;;
+  esac
+  exit 5
+fi
+
+if [ ! -f "$DOCKER_CMD" ]; then
+  echo "Command dependency 'docker' is not found/installed." >&2
+  echo -e "Visit ${BOLD}https://docs.docker.com/get-docker/${NORM} for installation." >&2
+  exit 4
+fi
 
 USAGE="command usage: $(basename $0) -r <PROFILE_PATH> -d <FASTQ_DIRECTORY>"
 
